### ISSUE TITLE
SQuAPP Undergoing Updates

### ISSUE THREAD

**Issue by daniella-patton** [LangeLab/SQuAPP#7]
I see this error when running the app both locally and through the link you shared. When will this app be updated?

Error:
We apologize for the inconvenience, but our application is currently undergoing updates.

Please check back later for new content.

**Comment by eneskemalergin** [comment]
If you want to initialize your local setup, change the "READY" variable to TRUE in the global.R file and run it on RStudio. However, I added this message because a few people reported bugs that broke the code. In addition to these bugs, one of the UI packages has been updated and no longer works with Shiny. Please try running with READY=TRUE and let me know if you encounter any of these issues.

**Comment by eneskemalergin** [comment]
The app has been updated and includes several bug fixes and error-handling messages. It should be more reliable than ever, but unforeseen issues may still arise. The online version of the app has been redirected to the updated version, so feel free to access it now. If you prefer to use the app locally, you can update your version to 0.3.

I am closing the issue for now, but if you experience any further problems, please open another issue so I can assist you.
